[package]
name = "hello-actix"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
clap = { version = "4.5.40", features = ["derive"] }
# rusqlite = "0.37.0"
serde = { version = "1.0", features = ["derive"] }
